# Generated by Django 4.0.4 on 2022-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_profile_address_profile_mobile_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit.\nMaecenas tortor mauris, maximus nec ipsum euismod, auctor vehicula ipsum.\n', max_length=135),
        ),
    ]
